spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=fixlt@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

server.port=8080

# Razorpay
razorpay.key-id=rzp_test_THHXBAxu9GQbYA
razorpay.key-secret=5OFCbZ9maomAMtVQzSbk8Oxm

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=faisalrok14@gmail.com
spring.mail.password=agvx fcmg bojm yuoi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=dr3i0bjgm
cloudinary.api-key=542489647912383
cloudinary.api-secret=E1naMfRElm1uWBmNfIafPu6Sz4o

# File Upload
file.upload-dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB